# Generated by Django 5.2.8 on 2025-11-20 23:27

import biblioteca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='fecha_publicacione',
        ),
        migrations.RemoveField(
            model_name='resena',
            name='clasificacion',
        ),
        migrations.AddField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resena',
            name='calificacion',
            field=models.IntegerField(default=0, validators=[biblioteca.models.validate_resena]),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=100, validators=[biblioteca.models.validate_autor]),
        ),
        migrations.AlterField(
            model_name='libro',
            name='resumen',
            field=models.TextField(validators=[biblioteca.models.validate_libro]),
        ),
    ]
